### ISSUE TITLE
Mexico COVID data series are not updating

### ISSUE THREAD

**Issue by ajxcameron** [mexicovid19/Mexico-datos#22]
The automatic updates to the Mexico data series have not occurred for the last 2 days.

**Comment by rodrigolece** [comment]
You are absolutely right. Sadly the Mexican Health Ministry changed the format in which they publish their data two days ago. I will have some time tomorrow to fix the code and get it working with the new format.

**Comment by rodrigolece** [comment]
Data is updated in dc4004e2a045168d0afc37b9ccd2fd94a27e23b1. I still need to get around the definition of suspected case and update the "sospechosos" time series, but everything else has been updated.

**Comment by ajxcameron** [comment]
Incredible. Thank you!
