### ISSUE TITLE
Información no actualizada

### ISSUE THREAD

**Issue by antoniozarate** [mexicovid19/Mexico-datos#33]
Buenos días,

Muchas gracias nuevamente por este gran esfuerzo de recolección de información. Me estoy dando cuenta que los datos se dejaron de actualizar desde el 31 de Mayo. 

Gracias!

**Comment by rodrigolece** [comment]
Hola Antonio! Una disculpa, pero el código tenía un bug que hizo que fallara con la base de datos del 27 de Mayo que ya está resuelto con 7fdcc87.

Fue un error también que se actalizara después de esto porque reflejó varios días acumulados. Ya está todo actualizado y en principio deberíamos de regresar a una actualización diaria.

Saludos!

**Comment by antoniozarate** [comment]
Nada que disculpar Rodrigo, en verdad el esfuerzo que han hecho es buenísimo!. Gracias por la pronta respuesta. Saludos!
