### ISSUE TITLE
Información no actualizada

### ISSUE THREAD

**Issue by antoniozarate** [mexicovid19/Mexico-datos#35]
Buenos días Rodrigo,

Nuevamente muy agradecido por este repositorio. Solo para comentarte que los datos no se han actualizado en más de una semana. Igual y ya se dieron cuenta, pero por si acaso.

De antemano muchas gracias y sauludos,
Antonio

**Comment by rodrigolece** [comment]
Hola Antonio, muchas gracias. Parece que la SSa cambió de nuevo algo porque la compresión parece ser inválida para cargarla desde Python. Por lo pronto me eché los días que faltaban a mano (commit a31057626f6a82e79f1070c5d45267d0d5eed602) pero espero poder tener un parche definitivo pronto.

Saludos!
