### ISSUE TITLE
Información sin actualizar

### ISSUE THREAD

**Issue by antoniozarate** [mexicovid19/Mexico-datos#36]
Buenos días Rodrigo, disculpa que vuelva a escribir, pero solo para saber si se podrá actualizar la información. Muchas gracias nuevamente!

**Comment by rodrigolece** [comment]
Una disculpa Antonio. Como te habrás dado cuenta ya llevo más de un mes sin poder actualizar la información... Lo siento mucho, pero creo que ya no es sostenible para mí seguirle dando mantenimiento a nuestra base de datos. 

Todo el código para correr las actualizaciones está en este repo y si necesitas ayuda dime y te puedo ayudar con lo que necesites. Saludos!

**Comment by antoniozarate** [comment]
Sí no te preocupes Rodrigo. Muchas gracias
